### PR TITLE
Partial Spanish Translation issue #404

### PR DESCRIPTION
**Pull request by fedGL**
I went to /docs and translated the root README.md file plus all 9 files inside the "advanced" folder.
The folders that now need Spanish translation are: api, examples, get-started, images.

### CODE REVIEW

**Comment by pmlopes** [comment]
Thanks, I'll wait for the remaining files and will merge before the end of hacktoberfest!

**Comment by fedGL** [comment]
Awesome. If nobody gets to it first, I'll continue translating files later today!

**Comment by fedGL** [comment]
Ok, that's a couple of folders more translated into Spanish. The only one missing is /get-started
Probably will do some time Saturday 😃

**Comment by fedGL** [comment]
That completes the translation into Spanish of /docs/advances, /docs/api, /docs/examples, /docs/get-started, /docs/images and /docs/README.md

**Comment by pmlopes** [comment]
Great!

One last request, can you add the Spanish config too?

https://github.com/reactiverse/es4x/blob/develop/docs/.vuepress/config.js#L42..L46

https://github.com/reactiverse/es4x/blob/develop/docs/.vuepress/config.js#L219..L307

Just like this example? 

After this we are complete to merge!

**Comment by fedGL** [comment]
Sure, I'll take a look

**Comment by fedGL** [comment]
Modified docs/.vuepress/config.js to include a 'es-ES' section in locales and a '/es/' section inside themeConfig just like the other languages. Hope that was helpful 😄

**Pull request merged**
