### PR TITLE
Docs/gr

### PR DESCRIPTION
**Pull request by AntoniosBarotsis**
Translated half of the documentation to Greek. As mentioned in [this reply](https://github.com/reactiverse/es4x/issues/404#issuecomment-699613814) of [this issue](https://github.com/reactiverse/es4x/issues/404), the second half will be finished by @Petros0

### CODE REVIEW

**Comment by AntoniosBarotsis** [comment]
I'm not sure if the second half will be added in this particular pr or if it will be a separate one but in any case I would ask you to consider merging this before Monday so it counts towards the 4 prs you have to make for hacktoberfest :)

**Comment by pmlopes** [comment]
@AntoniosBarotsis no worries, I'll wait a couple of days, but will merge within the hacktoberfest run.

**Comment by AntoniosBarotsis** [comment]
Thanks! Just a heads up: A pr is considered invalid if not merged within 7 days of it's creation!

**Comment by AntoniosBarotsis** [comment]
The second half of the translation has been posted [here](https://github.com/reactiverse/es4x/pull/414#issuecomment-702417874), this can be merged!

**Comment by pmlopes** [comment]
Thanks @AntoniosBarotsis 

The only missing step is the labels on the config:

https://github.com/reactiverse/es4x/blob/develop/docs/.vuepress/config.js#L397-L485

If you or @Petros0 can have a look, then a new PR is welcome!

Thanks!

**Pull request merged**
