### PR TITLE
Update ESModuleIO.java

### PR DESCRIPTION
**Pull request by laiweiwei**
Add 'export ...' and more 'import ...' syntax support.
```
@Test
  public void shouldAdaptImportDefault() {
    assertEquals(
      "const myModule = require('/modules/my-module.js').default;",
      ESModuleIO.adapt("import myModule from '/modules/my-module.js'"));
  }

  @Test
  public void shouldAdaptImportDefaultAndAlias() {
    assertEquals(
      "const def = require('/modules/my-module.js').default;const fn = require('/modules/my-module.js').fn;const shortName = require('/modules/my-module.js').fullName;",
      ESModuleIO.adapt("import def, { fn, fullName as shortName } from '/modules/my-module.js'"));
  }

  @Test
  public void shouldAdaptExport() {
    assertEquals(
      "const hello = (name) => `Hello ${name}`;\n"+
      "module.exports.hello = hello;module.exports.h = hello;",
      ESModuleIO.adapt(
        "const hello = (name) => `Hello ${name}`;\n"+
        "export { hello, hello as h }"));
  }

  @Test
  public void shouldAdaptExportDefaultVariable() {
    assertEquals(
      "const hello = (name) => `Hello ${name}`;\n"+
      "module.exports.default = hello;",
      ESModuleIO.adapt(
        "const hello = (name) => `Hello ${name}`;\n"+
          "export default hello;"));
  }

  @Test
  public void shouldAdaptExportDefaultFunctionDeclaration() {
    assertEquals(
      "module.exports.default = (name) => `Hello ${name}`;",
      ESModuleIO.adapt("export default (name) => `Hello ${name}`;"));
  }
```

### CODE REVIEW

**Comment by pmlopes** [comment]
@laiweiwei could you add the tests above to the pull request so we can have a check that it works as expected?

**Comment by frank-dspeed** [comment]
```js
      "const myModule = require('/modules/my-module.js').default;",
      ESModuleIO.adapt("import myModule from '/modules/my-module.js'"));
``` 
require does not export or uses default default only exists when we use dynamicImport or import with a CJS module as that gets shimed like

```js
module = { exports }
import('CJS')
return { default: module.exports}
```

**Comment by laiweiwei** [comment]
> ```js
>       "const myModule = require('/modules/my-module.js').default;",
>       ESModuleIO.adapt("import myModule from '/modules/my-module.js'"));
> ```
> 
> require does not export or uses default default only exists when we use dynamicImport or import with a CJS module as that gets shimed like
> 
> ```js
> module = { exports }
> import('CJS')
> return { default: module.exports}
> ```

we should use `import default` from the module that used `export default` or `module.exports.default`

```java 
@Test
public void shouldAdaptExportDefaultVariable() {
    assertEquals("const hello = (name) => `Hello ${name}`;\nmodule.exports.default = hello;",
      ESModuleIO.adapt("const hello = (name) => `Hello ${name}`;\nexport default hello;"));
}
```

**Comment by frank-dspeed** [comment]
@laiweiwei no NodeJS Coder will ever produce the line require().default from which code base did you got that idea?

Only when you load a CJS Module Inside esm <Module>{ default: module.exports } does happen any way we should focus on the require that is in graaljs and they understood it right you should look into the graal-require branch

**Comment by laiweiwei** [comment]
> @laiweiwei no NodeJS Coder will ever produce the line require().default from which code base did you got that idea?
> 
> Only when you load a CJS Module Inside esm { default: module.exports } does happen any way we should focus on the require that is in graaljs and they understood it right you should look into the graal-require branch

Yes, that's why the method name called `adapt`. This class itself is designed to be compatible with the syntax `import` and `export'` of `esm` in `.js` files

**Comment by laiweiwei** [comment]
By the way, the problem of `Dynamic Import` should handle its syntax in addition, and I don't think we should try to solve all the syntax of 'ESM' in '.js' files, developers should use '.mjs'.

As for why `esm` compatibility in '.js', I think this is to make it easier for front-end UI developers (Babel)

**Comment by frank-dspeed** [comment]
@laiweiwe i think the adapt method should get deprecated and not used it will not lead to working code you can not simply replace require import export statements there are more edge cases that apply often for example nested module.exports.nameModule = and all kind of other dynamic mutation i am working active on rollup maybe that is a name that you know. I am Familar with all that issues all custom Loaders should get implemented in the userland like rollup. 

having a function inside the runtime that unexpected changes code before it gets evaluated is a clear No GO!

**Comment by frank-dspeed** [comment]
```js
const firstExport = 'NowIamFirst';
module.exports = fistExport;
setTimeout(()=>module.exports='dynamicChanged after process.nextThick()');

(()=>module.exports = 'NowIam between firstExport and dynamicChanged')()
```

**Comment by frank-dspeed** [comment]
but ok i agree when only adapting import to require then this should be possible i have evaluated it now in my head as MJS is static it is no problem to translate it to require. :+1:

**Comment by pmlopes** [comment]
Merging the PR to help with interop :+1:

**Pull request merged**
